# Generated by Django 5.0.4 on 2024-09-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备管理', 'verbose_name_plural': '设备管理'},
        ),
        migrations.AlterModelTable(
            name='device',
            table='tb_devices',
        ),
    ]
