# Generated by Django 5.0.4 on 2024-09-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_is_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_login',
            field=models.BooleanField(default=True),
        ),
    ]
