# Generated by Django 5.0.4 on 2024-09-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_is_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='is_login',
            new_name='logged_in',
        ),
    ]
